import { Task, Teammate, User } from './types';

export const mockEmployeeTasks: Task[] = [
  {
    id: '1',
    title: 'Design Landing Page',
    description: 'Create wireframes and high-fidelity mockups for the main landing page',
    assignee: 'Maya Chen',
    priority: 'high',
    status: 'started',
    dueDate: '2024-04-10',
  },
  {
    id: '2',
    title: 'Review User Feedback',
    description: 'Analyze feedback from beta testers and compile report',
    assignee: 'Alex Rivera',
    priority: 'medium',
    status: 'started',
    dueDate: '2024-04-08',
  },
  {
    id: '3',
    title: 'Setup Analytics',
    description: 'Implement analytics tracking for user interactions',
    assignee: 'Jordan Lee',
    priority: 'medium',
    status: 'assigned',
    dueDate: '2024-04-15',
  },
  {
    id: '4',
    title: 'Create Icon Set',
    description: 'Design custom icons for the workspace interface',
    assignee: 'Casey Park',
    priority: 'low',
    status: 'completed',
    dueDate: '2024-04-05',
  },
  {
    id: '5',
    title: 'Documentation Sprint',
    description: 'Write comprehensive documentation for API endpoints',
    assignee: 'Morgan Smith',
    priority: 'medium',
    status: 'started',
    dueDate: '2024-04-12',
  },
  {
    id: '6',
    title: 'Performance Optimization',
    description: 'Optimize bundle size and improve page load times',
    assignee: 'Sam Johnson',
    priority: 'high',
    status: 'assigned',
    dueDate: '2024-04-20',
  },
];

export const mockTeammates: Teammate[] = [
  {
    id: '1',
    name: 'Maya Chen',
    role: 'UI Designer',
    status: 'active',
    avatar: 'MC',
    specialty: 'Interface Design',
  },
  {
    id: '2',
    name: 'Alex Rivera',
    role: 'Product Manager',
    status: 'active',
    avatar: 'AR',
    specialty: 'Product Strategy',
  },
  {
    id: '3',
    name: 'Jordan Lee',
    role: 'Frontend Engineer',
    status: 'away',
    avatar: 'JL',
    specialty: 'React & TypeScript',
  },
  {
    id: '4',
    name: 'Casey Park',
    role: 'Brand Designer',
    status: 'busy',
    avatar: 'CP',
    specialty: 'Visual Identity',
  },
  {
    id: '5',
    name: 'Morgan Smith',
    role: 'Tech Lead',
    status: 'active',
    avatar: 'MS',
    specialty: 'Architecture',
  },
  {
    id: '6',
    name: 'Sam Johnson',
    role: 'DevOps Engineer',
    status: 'offline',
    avatar: 'SJ',
    specialty: 'Infrastructure',
  },
];

export const mockCurrentEmployeeUser: User = {
  id: 'employee-1',
  name: 'Alex Rivera',
  role: 'employee',
  avatar: 'AR',
  level: 5,
  xp: 2450,
};

export const mockCurrentEmployerUser: User = {
  id: 'employer-1',
  name: 'Jordan Quinn',
  role: 'employer',
  avatar: 'JQ',
  level: 8,
  xp: 5200,
};

export const mockEmployerTasks: Task[] = [
  {
    id: 'e1',
    title: 'Review Q2 Performance',
    description: 'Evaluate team performance metrics and set new KPIs',
    assignee: 'Jordan Quinn',
    priority: 'high',
    status: 'started',
    dueDate: '2024-04-08',
  },
  {
    id: 'e2',
    title: 'Assign Sprint Tasks',
    description: 'Create and assign tasks for the upcoming sprint',
    assignee: 'Jordan Quinn',
    priority: 'high',
    status: 'started',
    dueDate: '2024-04-07',
  },
  {
    id: 'e3',
    title: 'Team Standup',
    description: 'Conduct daily standup meeting with the team',
    assignee: 'Jordan Quinn',
    priority: 'medium',
    status: 'assigned',
    dueDate: '2024-04-04',
  },
  {
    id: 'e4',
    title: 'Budget Allocation',
    description: 'Review and approve budget for tools and resources',
    assignee: 'Jordan Quinn',
    priority: 'high',
    status: 'assigned',
    dueDate: '2024-04-15',
  },
  {
    id: 'e5',
    title: 'One-on-Ones',
    description: 'Schedule and conduct individual check-ins with team members',
    assignee: 'Jordan Quinn',
    priority: 'medium',
    status: 'started',
    dueDate: '2024-04-12',
  },
];
